# Site
repository: Jonghakseo/modern-resume-theme
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Jonghak Seo
title: Web front engineer
email: unqocn@gmail.com
# email_title: Email (Email title override)
phone: +82 10-4129-7219
# phone_title: Phone (Phone title override)
website: nookpi.tistory.com
website_title: Blog

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: jekyllrb
github_username:  jonghakseo
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
linkedin_username: jong-hak-seo-9142ba200
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#orcid_username: 0000-0000-0000-0000
#googlescholar_username: D847cGsAAAAJ

# Additional icon links
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  React와 TypeScript를 즐겨 사용하는 3년 차 웹 프론트엔드 개발자입니다. 
  
  테스트 코드 작성이 개발자의 성장과 서비스의 견고함에 기여한다고 생각합니다. Jest, RTL 등을 사용해 사용자 관점의 테스트 코드를 작성하는 것을 좋아합니다.

  유연한 설계와 컴포넌트의 역할 분리를 통한 코어 로직의 재사용성에 관심이 많으며, 사고가 구현에 종속되지 않기 위해 언어, 프레임워크, 라이브러리의 동작에 대한 세부 지식을 함양하기 위해 노력합니다.
  
  서비스 기업에서 비즈니스 임팩트를 내기 위해서는 능동적이고 적극적인 커뮤니케이션과 업무 수행이 필요하다고 생각하며, 그러한 동료들과 함께 일하는 환경을 선호합니다.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Creatrip, Inc.
        link: https://www.creatrip.com/
        link_text: creatrip web
        caption: 2021.12 ~
        quote: >
          다국어 서비스인 Creatrip 개발 및 유지보수
        description: | # this will include new lines to allow paragraphs
          - 어학당 도메인 개발 및 유지보수
          - 숙소 도메인 개발 및 유지보수
          - 관리팀 업무 수행
          - 2022 상반기/하반기 리뷰 Hyper 인센티브 대상자 선정 (사내 상위 10%)

      - layout: left
        title: Slogup, Inc.
        link: https://www.slogup.com/
        link_text: slogup web
        caption: 2020.09 ~ 2021.12
        quote: >
          자체 서비스인 쓱싹 및 SK 렌터카 다이렉트 등 외주 서비스 개발
        description: | # this will include new lines to allow paragraphs
          - 쓱싹 2.0 리뉴얼 작업
          - SK 렌터카 다이렉트 B2C 서비스 전체 개발


  - title: Projects
    layout: list
    content:
      - layout: left
        title: Creatrip
        sub_title: TypeScript, NextJS, Apollo Client, styled-components, Storybook, Jest, rtl, Github Actions
        link: https://www.creatrip.com
        quote: >
          MAU 170만. 7개국 유저에게 여행, 직구, 어학당, 숙소 서비스
        description: | # this will include new lines to allow paragraphs
          **어학당 스쿼드**
          - 어학당 신청에 필요한 전반적인 프론트 기능 구현
            - 학교마다 다른 신청서 작성 폼 렌더링을 위히 서버 동적 데이터를 바탕으로 폼 렌더링 및 검증, 임시저장을 위한 상태 저장 및 복원 기능 구현
          - 컴포넌트 및 핵심 비즈니스 로직에 대한 테스트 코드 작성
            - 신청서 폼에 사용되는 컴포넌트들의 유닛 테스트 및 신청서 폼 통합 테스트 커버리지 100% 유지
          - OpenAI LLM 기반 어학당 챗봇 POC
            - document split, vector embeddings, retriver에 langchain 사용
          
          **숙소 스쿼드**
          - 숙소 검색 및 예약에 필요한 전반적인 프론트 기능 구현
            - 숙소 검색 리스트, 지도로 보기 화면 구현
            - 숙소 상세 페이지 캘린더 구현
          - 클라이언트 클러스터링 기능을 갖춘 Google Map 기반 지도 컴포넌트 구현
            - ZOOM LEVEL에 따른 클러스터링 범위 설정, 일정 범위 내 숙소에 대해 child node로 병합시키는 방식 사용
          
          **프론트엔드 관리팀**
          - 성능 개선을 위한 Web Vitals 모니터링 및 주요 인덱스 페이지 SSG 전환으로 LCP 70% 개선
            - next 내장 reportWebVitals + ga 사용하여 측정
          - A/B test를 위한 Growthbook 도입 및 전사 적용
          - 런타임 에러 트래킹을 위한 Sentry 도입
            - 도입 후 2주간 unhandled SSR 에러 95% 절감
            - 구글 번역 익스텐션 이슈 발견 후 Node prototype function override 방식으로 대응
          - 공통 컴포넌트 개발 및 유지보수
            - Text, Button, Toast, Tooltip, Calendar 등
            - Toast 구현시 애니메이션 reverse를 위한 코드 작성 중, raf 콜백 실행 위치로 인해 발생한 버그 해결
          - AST 파싱을 통한 사내 eslint-plugin 패키지 구현 (@creatrip/eslint-plugin)
            - component props naming, restrict domain model property 구현
          - Github custom actions를 통해 팀 내 반복 작업 자동화
            - 공통 변경사항에 대한 Slack 알림, 정적 파일 유효성 검증, Jira 티켓 바인딩, Storybook 배포 등
          - 디자인 팀과의 협업을 위한 Storybook 구축
            - 상수값 모킹 및 외부 노출을 막기 위해 webpack.resolve.alias + proxy 사용
          - 그로스 팀의 Google Analytics Event 명세를 ts 코드로 생성하는 generator 구현
          - Creatrip 유튜브 SRT 자막 번역 초안을 위한 사내 프로덕트 구현

      - layout: left
        title: SK 렌터카 Direct
        sub_title: TypeScript, NextJS, SWR, styled-components
        link: https://www.skdirect.co.kr/
        quote: >
          최대 일 거래액 200억 이상의 비대면 렌터카 견적 비교 및 계약 서비스
        description: | # this will include new lines to allow paragraphs
          **유저페이지**
          - 프로젝트 초기 세팅부터 전체 기능 전담 개발
          - 차량별 견적 비교 및 결제 프로세스
          - 개인/법인/개인사업자별 계약 프로세스
          
          다양한 SSR 이슈 트래킹 및 해결
          GTmetrix 측정 기반 웹 퍼포먼스 최적화
          - 트리셰이킹, 이미지 지연 로드, 리액트 렌더링 최적화, 서드파티 스크립트 defer 처리
          - 퍼포먼스 벤치마크 등급 기준 F -> B로 개선

      - layout: left
        title: 쓱싹 2.0
        link: https://sgsg.slogup.com/
        sub_title: TypeScript, Create React App, styled-components
        quote: >
          총 거래금액 200억 이상의 비대면 가전 설치 및 시공 예약 서비스
        description: | # this will include new lines to allow paragraphs
          **유저페이지**
          - 메인 페이지 및 카테고리별 랜딩 페이지
          - 로그인 및 마이페이지
          
          **사내 생산성 증진을 위한 자발적 태스크**
          - 사내 노션 table 조회 후 react helmet과 연동: SEO 관리가 가능한 노션 페이지 추가
          - 프로젝트 내 Asset 관리를 위한 사내 라이브러리 개발 (@slogup/asset-manager)
          - 고객 상담에 필요한 녹취록 작성 프로그램 제작 (Electron, Google STT 사용)

  - title: Ability
    layout: list
    content:
      - layout: left
        title: 웹 애플리케이션 설계
        sub_title: React
        description: | # this will include new lines to allow paragraphs
          - 역할과 책임에 근거한 컴포넌트 설계로 재사용성과 확장성 추구
          - IoC 패턴을 사용한 컴포넌트 의존성 주입에 대한 이해
          - 비즈니스 로직과 UI 관심사 분리를 위한 선언적인 코드 지향

      - layout: left
        title: 테스트 코드 작성
        sub_title: Jest, react-testing-library
        description: | # this will include new lines to allow paragraphs
          - 세부 구현에 의존하지 않는 유저 관점의 유지보수 가능한 테스트 코드 작성
          - 유닛 테스트 가능한 컴포넌트 작성
          - 테스트 환경과 도구에 대한 이해를 바탕으로 한 테스트 환경의 다양한 이슈 해결 경험 보유
            - 1년간 React 테스트를 작성하며 겪은 이슈 10가지 (https://nookpi.tistory.com/161)
            - 반응형 UI에 대처하는 테스트의 자세 (https://nookpi.tistory.com/139)
            - 레이아웃 훅 수정이 결제 버튼 테스트에 영향을 미치는 이유 (https://nookpi.tistory.com/150)

  - title: Personal Projects
    layout: list
    content:
      - layout: left
        title: Drag GPT
        sub_title: Drag GPT - Easy start AI with Drag!
        caption: 2023.02 ~
        link: https://chrome.google.com/webstore/detail/draggpt-easy-start-with-d/akgdgnhlglhelinkmnmiakgccdkghjbh
        link_text: chrome webstore
        description: |
          웹에서 one-shot prompt 요청을 쉽게 사용할 수 있도록 크롬 익스텐션 제작
          
          사전에 작성한 프롬프트를 드래그로 선택된 텍스트를 포함하여 요청

      - layout: left
        title: Chrome Extension Boilerplate
        sub_title: Chrome Extension Boilerplate with React + Vite + TypeScript
        caption: 2022.07 ~
        link: https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite
        link_text: chrome-extension-boilerplate-react-vite
        description: |
          크롬 익스텐션을 편하게 만들기 위한 보일러 플레이트
          
          크롬 익스텐션을 처음 개발하는 사람들이 쉽게 사용할 수 있도록 하는 데 초점을 맞춤
          
          - Star 750 ▲
          - Vite(with Rollup), React18, Typescript, Jest, RTL, Sass, Tailwind 등의 기술 스택 적용
          - HRR(Hot Rebuild & Refresh/Reload) 자체 구현
          - 1년간 메인테이너로써 약 40건의 이슈 대응

      - layout: left
        title: note-for.me
        sub_title: Custom MD editor
        caption: 2022. 01
        link: https://the-work.space/
        description: | 
          웹 기반으로 사용하기 위해 만든 마크다운 에디터
          
          - Toast UI editor 커스텀해서 사용
            - 다크모드
            - 작성 글 Gist 업로드
            - 이미지, 동영상 업로드
          - amplify로 배포

#      - layout: left
#        title: Namu's Pick
#        sub_title: Share Playlist and Music Player
#        caption: 2021.07 ~ 2021.12
#        link: https://nookpi.tistory.com/106
#        quote: >
#          플레이리스트 공유, 음악재생 및 채팅
#        description: |
#          - 여자친구의 추천곡을 보관하고 듣기 위해 제작
#          - 유튜브 URL 입력 -> 가수, 곡명을 파싱 -> 홈 서버에 음원 저장
#          - 재생목록 공유 및 하고 음악 재생 가능
#          - 크롬 익스텐션 버전, React Native App 버전 2가지 개발
      - layout: left
        title: ZZaplin
        sub_title: Web Layout visualizer like a Zeplin
        caption: 2020.11
        link: https://chrome.google.com/webstore/detail/ryans-zzaplin/mbpmgelfipjfedefldiblikoenhpjfgb?hl=ko
        link_text: chrome webstore
        description: | 
          Element간 간격을 재기 위한 익스텐션으로 Zeplin에서 영감을 받아 jQuery로 제작

  - title: Education
    layout: list
    content:
      - layout: left
        title: 경희대학교 경영학
        caption: 2010 ~
        description: |
          - 학사경고 누적으로 인한 제적(2021)

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
