name: Update Dependencies
on:
  repository_dispatch:
    types: [create-pull-request]
jobs:
  update-dep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
#      - uses: actions/setup-node@v3
#        with:
#          node-version: '16.x'
      - name: Set up Ruby
        run: rm ./README.md
        # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
        # change this to (see https://github.com/ruby/setup-ruby#versioning):
#        uses: ruby/setup-ruby@v1
#        with:
#          ruby-version: 2.6
#      - name: Update dependencies
#        run: |
#          bundle config path vendor/bundle
#          bundle install --jobs 4 --retry 3
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PAT }}
          commit-message: Update dependencies
          title: Update dependencies
          body: |
            - Dependency updates
            
            Auto-generated by [create-pull-request][1]
            
            [1]: https://github.com/peter-evans/create-pull-request
          branch: update-dependencies
